// product
export const getAllProduct = 'GET_ALL_PRODUCT_FULFILLED'
export const getAllProductPending = 'GET_ALL_PRODUCT_PENDING'
export const getAllProductError = 'GET_ALL_PRODUCT_REJECTED'
export const getDetailProduct = 'GET_DETAIL_PRODUCT_FULFILLED'
export const getDetailProductPending = 'GET_DETAIL_PRODUCT_PENDING'
export const getDetailProductError = 'GET_DETAIL_PRODUCT_REJECTED'
export const categoryProduct = 'GET_CATEGORY_PRODUCT_FULFILLED'
export const categoryProductPending = 'GET_CATEGORY_PRODUCT_PENDING'
export const categoryProductError = 'GET_CATEGORY_PRODUCT_REJECTED'
// cart
export const insertCart = 'INSERT_CART'
export const deleteCart = 'DELETE_CART'
// user
export const getAllUser = 'GET_ALL_USER_FULFILLED'
export const getAllUserPending = 'GET_ALL_USER_PENDING'
export const getAllUserError = 'GET_ALL_USER_REJECTED'
export const getDetailUser = 'GET_DETAIL_USER_FULFILLED'
export const getDetailUserPending = 'GET_DETAIL_USER_PENDING'
export const getDetailUserError = 'GET_DETAIL_USER_REJECTED'
// transaction
export const getAllTransaction = 'GET_ALL_TRANSACTION_FULFILLED'
export const getAllTransactionPending = 'GET_ALL_TRANSACTION_PENDING'
export const getAllTransactionError = 'GET_ALL_TRANSACTION_REJECTED'
export const getDetailMasterTr = 'GET_DETAIL_TRANSACTION_MASTER_FULFILLED'
export const getDetailMasterTrPending = 'GET_DETAIL_TRANSACTION_MASTER_PENDING'
export const getDetailMasterTrError = 'GET_DETAIL_TRANSACTION_MASTER_REJECTED'
export const getDetailTr = 'GET_DETAIL_TRANSACTION_FULFILLED'
export const getDetailTrPending = 'GET_DETAIL_TRANSACTION_PENDING'
export const getDetailTrError = 'GET_DETAIL_TRANSACTION_REJECTED'
// promo
export const getAllPromo = 'GET_ALL_PROMO_FULFILLED'
export const getAllPromoPending = 'GET_ALL_PROMO_PENDING'
export const getAllPromoError = 'GET_ALL_PROMO_REJECTED'
export const getDetailPromo = 'GET_DETAIL_PROMO_FULFILLED'
export const getDetailPromoPending = 'GET_DETAIL_PROMO_PENDING'
export const getDetailPromoError = 'GET_DETAIL_PROMO_REJECTED'
